### ISSUE TITLE
Inhaltliche Beschreibung - Editor funktioniert nicht

### ISSUE THREAD

**Issue by DorianWo** [Projekt-Modulhandbuch/ModulhandbuchManager#7]
Bei Modulen die bereits einen Text im Feld **Inhaltliche Beschreibung** haben ( Beispielsweise Grundlagen der Wirtschaftsinformatik oder Grundlagen der Software-Entwicklung), ist es möglich den Text über den Editor zu bearbeiten oder zu löschen. Bei Modulen die keinen Text in **Inhaltliche Beschreibung** haben, sowie bei neu angelegten Modulen ist dies nicht möglich.
![grafik](https://user-images.githubusercontent.com/73701366/105633147-43f18700-5e57-11eb-8cf7-5d68446974bf.png)

**Comment by cptnuss-ops** [comment]
Done with SQL-Rework branch. To be released... @DorianWo
