### ISSUE TITLE
 Art und Form der Prüfung - Fehler beim Speichern

### ISSUE THREAD

**Issue by DorianWo** [Projekt-Modulhandbuch/ModulhandbuchManager#8]
**Art und Form der Prüfung** lässt sich nicht aufgrund der Änderung an den Spalten **Verbindlichkeit | Art | Form |** nicht mehr speichern.

![grafik](https://user-images.githubusercontent.com/73701366/105633448-ececb180-5e58-11eb-9dbc-21ac4a44f84e.png)

**Comment by cptnuss-ops** [comment]
Done with integration of @FabianSpitzka SQL concept.
