### ISSUE TITLE
Bearbeiten von Moduldaten - Buttons verblassen nicht

### ISSUE THREAD

**Issue by DorianWo** [Projekt-Modulhandbuch/ModulhandbuchManager#9]
Nach klicken auf Bearbeiten und anschließendem klicken auf Speichern, verblassen die Buttons Verwerfen und Speichern nicht.
Bei Lernziele, Schlüsselqualifikationen, u.a funktioniert es.

![grafik](https://user-images.githubusercontent.com/73701366/105726613-8768f580-5f2a-11eb-8b3c-38f3294aabcf.png)

**Comment by cptnuss-ops** [comment]
Done with SQL Rework. To be released... @DorianWo
